DocumentFlow/Models/Executor.cs
namespace DocumentFlow.Models;

public class Executor
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public int Code { get; set; }
    public DateTime? DateOfOrder { get; set; }
    public Guid DocumentId { get; set; }
    public string ExecutionTime { get; set; }
    public string Description { get; set; }
    public string? Cause { get; set; }
    public string ExecutorRole { get; set; }
    public DateTime CreatedAt { get; set; }
    public int StatusId { get; set; }

    public virtual User User { get; set; }
    public virtual Document Document { get; set; }
    public virtual Status Status { get; set; }
}

DocumentFlow/Models/ViewModels/Executor/CreateExecutorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DocumentFlow.Models.ViewModels.Executor;

public class CreateExecutorViewModel
{
    
    public List<Models.User> Users { get; set; }
    [Required]
    public List<Guid> UserId { get; set; }
    public int Code { get; set; }
    public DateTime DateOfOrder { get; set; }
    [Required]
    public Guid DocumentId { get; set; }
    [Required]
    public string ExecutionTime { get; set; }
    [Required]
    public string Description { get; set; }
}

DocumentFlow/Models/ViewModels/Executor/RejectViewModel.cs
namespace DocumentFlow.Models.ViewModels.Executor;

public class RejectViewModel
{
    public string Description { get; set; }
}

DocumentFlow/Controllers/ExecutorController.cs
using DocumentFlow.Models;
using DocumentFlow.Models.ViewModels.Executor;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DocumentFlow.Controllers;

public class ExecutorController : BaseController
{
    private readonly DataContext _dataContext;

    public ExecutorController(DataContext dataContext)
    {
        _dataContext = dataContext;
    }

    [HttpGet]
    [Authorize]
    public IActionResult Create(Guid id,Guid departmentId)
    {
        var currentUserId = GetCurrentUserId();
        var users = _dataContext.Users.Where(x=>x.Id != currentUserId && x.RoleId == 3 && x.DepartmentId.Equals(departmentId)).OrderBy(x=>x.CreatedAt).ToList();
        var executor = new CreateExecutorViewModel()
        {
            Users = users,
            DocumentId = id,
            Code = NumberGenerator(5)
        };
        return View(executor);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Create(CreateExecutorViewModel model)
    {
        
        foreach (var userId in model.UserId)
        {
            var user = await _dataContext.Users.FindAsync(userId);
            var executor = new Executor()
            {
                Id = Guid.NewGuid(),
                Code = model.Code,
                Description = model.Description,
                DocumentId = model.DocumentId,
                StatusId = 1,
                CreatedAt = DateTime.UtcNow,
                ExecutionTime = model.ExecutionTime,
                ExecutorRole = user!.Role.Name,
                UserId = userId,
                DateOfOrder = DateTime.UtcNow
            };
            await _dataContext.AddAsync(executor);
            await _dataContext.SaveChangesAsync();
           await CreateNotion(userId, executor.DocumentId, executor.Description);
           await ChangeDocumentStatus(executor.DocumentId);
        }
        return RedirectToAction("GetAll","Document");
    }

    private async Task ChangeDocumentStatus(Guid documentId)
    {
        var document = await _dataContext.Documents.FindAsync(documentId);
        document!.StatusId = 2;
        await _dataContext.SaveChangesAsync();
    }

    private async Task CreateNotion(Guid userId, Guid documentId, string description)
    {
        var notion = new Notion()
        {
            Id = Guid.NewGuid(),
            Message = description,
            UserId = userId,
            DocumentId = documentId
        };
        await _dataContext.AddAsync(notion);
        await _dataContext.SaveChangesAsync();
    }
    
    private static int NumberGenerator(int i)
    {
        if (i < 2)
        {
            throw new Exception("digitsCount must be greater than or equal to 2");
        }
        var min = Math.Pow(10, i - 1);
        var max = Math.Pow(10, i) - 1;
        var random = new Random();
        return random.Next((int)min, (int)max);
    }
}

DocumentFlow/Views/Executor/Create.cshtml
@model DocumentFlow.Models.ViewModels.Executor.CreateExecutorViewModel

@{
    Layout = "_Layout";
}
<link rel="stylesheet" type="text/css" href="~/plugins/select2/select2.min.css">
 <link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
    <link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
<div class="mx-4" style="width: 50%;">
    <h3>Добавление исполнителя</h3>

    <form class="form-vertical" enctype="multipart/form-data" asp-action="Create" asp-controller="Executor" method="post">
        <div style="color: red" asp-validation-summary="ModelOnly"></div>
        <input type="hidden" name="documentId" asp-for="DocumentId" class="form-control">
        <div class="form-group mb-4">
            <label class="control-label">Описание:</label>
            <input type="text" name="description" asp-for="Description" class="form-control">
        </div>
        <div class="form-group mb-4">
            <label class="control-label">Код:</label>
            <input type="number" readonly name="code" asp-for="Code" class="form-control">
        </div>
        <div class="form-group mb-4">
            <label class="control-label">Дата:</label>
              <input id="basicFlatpickr" asp-for="ExecutionTime" class="form-control flatpickr flatpickr-input active" type="text" placeholder="Select Date..">
        </div>
        <div class="form-group mb-4">
            <label class="control-label">Исполнитель:</label>
            <select asp-for="UserId" class="form-control tagging" multiple="multiple">
                @foreach (var users in Model.Users)
                {
                    <option value="@users.Id">@users.Name</option>
                }
            </select>
        </div>
        <input type="submit" value="Добавить" class="btn btn-primary ml-3 mt-3">
    </form>
</div>


@await Html.PartialAsync("_ScriptsPartial")

<script src="~/plugins/select2/select2.min.js"></script>
<script src="~/plugins/flatpickr/flatpickr.js"></script>
  <script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script>
 $(".tagging").select2({
        tags: true
    });
</script>
<script>
var f3 = flatpickr(document.getElementById('rangeCalendarFlatpickr'), {
    mode: "range"
});
</script>